
package Vista;

import Controlador.Manejador_asignar;
import Controlador.Manejador_productos;
import Bitacora.*;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author usuario
 */
public class Asignar_Productos extends javax.swing.JFrame {
    private Manejador_asignar controlador = new Manejador_asignar();
    private Manejador_productos listado = new Manejador_productos();
    private Registro bitacora = new Registro();
    /**
     * Creates new form 
     */
    public Asignar_Productos() {
        this.setName("Asignar_productos");
        initComponents();
        bitacora.Escribir(this.getName(), "Inicio sin lista - no debe pasar esto");
    } 
    public Asignar_Productos(Manejador_productos productos) {
        this.setName("Asignar_productos");
        bitacora.Escribir(this.getName(), "Inicio con una lista que referenciar - correcto");
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        producto_1_text = new javax.swing.JTextField();
        producto_2_text = new javax.swing.JTextField();
        producto_3_text = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        directorio_text = new javax.swing.JTextField();
        B_cancelar = new javax.swing.JButton();
        B_confirmar = new javax.swing.JButton();
        B_buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        B_buscarCarpeta = new javax.swing.JButton();
        directorio_Carpeta = new javax.swing.JTextField();
        Registros_1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        registro_1_text = new javax.swing.JTextField();
        registro_2_text = new javax.swing.JTextField();
        registro_3_text = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Producto 1");

        jLabel2.setText("Producto 2");

        jLabel3.setText("Producto 3");

        producto_1_text.setEditable(false);
        producto_1_text.setAutoscrolls(false);

        producto_2_text.setEditable(false);
        producto_2_text.setAutoscrolls(false);

        producto_3_text.setEditable(false);
        producto_3_text.setAutoscrolls(false);
        producto_3_text.setFocusTraversalPolicyProvider(true);
        producto_3_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                producto_3_textActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        jLabel6.setText("Directorio");

        directorio_text.setEditable(false);
        directorio_text.setText("Busca en el boton");
        directorio_text.setAutoscrolls(false);

        B_cancelar.setText("Cancelar");
        B_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cancelarActionPerformed(evt);
            }
        });

        B_confirmar.setText("Confirmar");
        B_confirmar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        B_confirmar.setEnabled(false);
        B_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_confirmarActionPerformed(evt);
            }
        });

        B_buscar.setText("Buscar");
        B_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_buscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Archivo txt");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei", 3, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Carpeta de Registros");

        B_buscarCarpeta.setText("Buscar");
        B_buscarCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_buscarCarpetaActionPerformed(evt);
            }
        });

        directorio_Carpeta.setEditable(false);
        directorio_Carpeta.setText("Busca en el boton");
        directorio_Carpeta.setAutoscrolls(false);

        Registros_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registros_1.setText("Registros 1");
        Registros_1.setToolTipText("");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registros 2");
        jLabel8.setToolTipText("");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Registros 3");
        jLabel9.setToolTipText("");

        registro_1_text.setEditable(false);
        registro_1_text.setAutoscrolls(false);

        registro_2_text.setEditable(false);
        registro_2_text.setAutoscrolls(false);

        registro_3_text.setEditable(false);
        registro_3_text.setAutoscrolls(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(B_cancelar)
                .addGap(85, 85, 85)
                .addComponent(B_confirmar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(107, 107, 107)
                .addComponent(jLabel3)
                .addGap(77, 77, 77))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Registros_1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(registro_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(B_buscarCarpeta)
                                .addGap(26, 26, 26)
                                .addComponent(directorio_Carpeta)))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registro_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(registro_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(B_buscar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(directorio_text))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(producto_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(producto_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(producto_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(directorio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_buscar))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producto_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(producto_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(producto_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(directorio_Carpeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_buscarCarpeta))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Registros_1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registro_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registro_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registro_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_cancelar)
                    .addComponent(B_confirmar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void producto_3_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_producto_3_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_producto_3_textActionPerformed

    private void B_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_confirmarActionPerformed
        
        listado.agregar_a_lista(producto_1_text.getText(),(directorio_Carpeta.getText() +"\\" + registro_1_text.getText()));
        listado.agregar_a_lista(producto_2_text.getText(),(directorio_Carpeta.getText() +"\\" + registro_2_text.getText()));
        listado.agregar_a_lista(producto_3_text.getText(),(directorio_Carpeta.getText() +"\\" + registro_3_text.getText()));
        bitacora.Escribir(this.getName(), "Se obtiene los nombres y direcciones de almacenamiento de los productos");
        controlador.registrar_historial();
        dispose();
    }//GEN-LAST:event_B_confirmarActionPerformed

    private void B_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_buscarActionPerformed
        // Proceso de busqueda de un archivo
        bitacora.Escribir(this.getName(), "Se abre buscador de archivo");
        JFileChooser buscador = new JFileChooser();
        int respuesta = buscador.showOpenDialog(this);
        if(respuesta == JFileChooser.APPROVE_OPTION){
            bitacora.Escribir(this.getName(), "Se selecciono un archivo");
            File productos_txt = buscador.getSelectedFile();
            directorio_text.setText(productos_txt.getAbsolutePath());
            Nombrar_productos(productos_txt);
        }else{
            bitacora.Escribir(this.getName(), "Falla buscador de archivo");
            directorio_text.setText("El archivo seleccionado no puede utilizarce");
        }
        habilitar_confirmar();
    }//GEN-LAST:event_B_buscarActionPerformed

    private void B_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cancelarActionPerformed
        dispose();
        bitacora.Escribir(this.getName(), "Se suspende la ventana y deja de ser visible");
    }//GEN-LAST:event_B_cancelarActionPerformed

    private void B_buscarCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_buscarCarpetaActionPerformed
        //Processo de busqueda de un directorio/carpeta
        bitacora.Escribir(this.getName(), "Se abre buscador de carpeta");
        JFileChooser buscador = new JFileChooser();
        buscador.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int respuesta = buscador.showOpenDialog(this);
        if(respuesta == JFileChooser.APPROVE_OPTION){
            bitacora.Escribir(this.getName(), "Se sleecciono una carpeta");
            File carpeta_registros = buscador.getSelectedFile();
            directorio_Carpeta.setText(carpeta_registros.getAbsolutePath());
            Nombrar_Registros(carpeta_registros);
        }else{
            bitacora.Escribir(this.getName(), "Falla en la busqueda de carpeta");
            directorio_Carpeta.setText("El archivo seleccionado no puede utilizarce");
        }
        habilitar_confirmar();
    }//GEN-LAST:event_B_buscarCarpetaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_buscar;
    private javax.swing.JButton B_buscarCarpeta;
    private javax.swing.JButton B_cancelar;
    public javax.swing.JButton B_confirmar;
    private javax.swing.JLabel Registros_1;
    private javax.swing.JTextField directorio_Carpeta;
    private javax.swing.JTextField directorio_text;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField producto_1_text;
    private javax.swing.JTextField producto_2_text;
    private javax.swing.JTextField producto_3_text;
    private javax.swing.JTextField registro_1_text;
    private javax.swing.JTextField registro_2_text;
    private javax.swing.JTextField registro_3_text;
    // End of variables declaration//GEN-END:variables

    private void Nombrar_productos(File Productos_file) {
        String[] nombres = controlador.Nombrar_productos(Productos_file);
        producto_1_text.setText(nombres[0]);
        producto_2_text.setText(nombres[1]);
        producto_3_text.setText(nombres[2]);
        bitacora.Escribir(this.getName(), "Se asigno nombre a la lista de los productos correctamente");
    }

    private void Nombrar_Registros(File Carpeta) {
        String[] registros_directorio = controlador.Registros(Carpeta);
        registro_1_text.setText(registros_directorio[0]);
        registro_2_text.setText(registros_directorio[1]);
        registro_3_text.setText(registros_directorio[2]);
        bitacora.Escribir(this.getName(), "Se asigno el directorio de su archivo txt de cada producto");
        
    }

    private void habilitar_confirmar() {
        bitacora.Escribir(this.getName(), "Se comprueba si se puede habilitar el boton confirmar");
        if(!productos_vacios() && !registros_vacios()){
            bitacora.Escribir(this.getName(), "Se habilita el boton confirmar");
            B_confirmar.setEnabled(rootPaneCheckingEnabled);
        }
    }

    private boolean productos_vacios() {
      return (producto_1_text.getText().equals("")) && !(producto_2_text.getText().equals("")) && !(producto_3_text.getText().equals(""));
    }

    private boolean registros_vacios() {
        return (registro_1_text.getText().equals("")) && !(registro_2_text.getText().equals("")) && !(registro_3_text.getText().equals(""));
    }

    public Manejador_productos obtener_productos() { // Devuelve datos a la ventana Votaciones
        bitacora.Escribir(this.getName(), "Se devuelve el listado de productos nuevo");
        return listado;
    }
}

