package Vista;

import Bitacora.Registro;
import Controlador.Manejador_productos;
import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author usuario
 */
public class Pastel_grafica extends javax.swing.JFrame {
    private Manejador_productos listado = null;
    final int GRADOS_CIRCULO = 360;
    private Registro bitacora = new Registro();

    /**
     * Creates new form Graficas
     */
    public Pastel_grafica(Manejador_productos productos) {
        this.setName("Pastel");
        bitacora.Escribir(this.getName(), "Se inicio con productos a modelar");
        initComponents();
        this.setLocationRelativeTo(null);
        listado = productos;
    }
    
    public Pastel_grafica() {
        this.setName("Pastel");
        bitacora.Escribir(this.getName(), "Sin productos - esta mal");
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    boolean pintar_grafica = true;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B_cerrar = new javax.swing.JButton();
        B_Refrescar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Grafica de Pastel");

        jLabel1.setText("Votaciones al momento");

        B_cerrar.setText("Cerrar");
        B_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_cerrarActionPerformed(evt);
            }
        });

        B_Refrescar.setText("Refrescar");
        B_Refrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_RefrescarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(B_cerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(B_Refrescar)
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_cerrar)
                    .addComponent(B_Refrescar))
                .addGap(71, 71, 71))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_cerrarActionPerformed
        dispose();
        bitacora.Escribir(this.getName(), "Se suspende y deja de ser visible");
    }//GEN-LAST:event_B_cerrarActionPerformed

    private void B_RefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_RefrescarActionPerformed
        repaint();
        bitacora.Escribir(this.getName(), "Se actualizo");
    }//GEN-LAST:event_B_RefrescarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Refrescar;
    private javax.swing.JButton B_cerrar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public void paint(Graphics g){
        super.paint(g);
        if(pintar_grafica){
            bitacora.Escribir(this.getName(), "Se grafican los datos");
            String rojo = listado.Producto_1().getNombre();
            String verde = listado.Producto_2().getNombre();
            String azul = listado.Producto_3().getNombre();
            
            int num_rojo = listado.Producto_1().getVotos();
            int num_verde = listado.Producto_2().getVotos();
            int num_azul = listado.Producto_3().getVotos();
            
            int total_votos = num_rojo + num_verde + num_azul;
            
            int grados_rojo = num_rojo * GRADOS_CIRCULO / total_votos;
            int grados_verde = num_verde * GRADOS_CIRCULO / total_votos;
            int grados_azul = num_azul * GRADOS_CIRCULO / total_votos;
            
            g.setColor(new Color(255,0,0));
            g.fillArc(25, 80, 200, 200, 0, grados_rojo);
            g.fillRect(250, 120, 20, 20);
            g.drawString(listado.Producto_1().getNombre(),275,135);
            
            g.setColor(new Color(0,130,0));
            g.fillArc(25, 80, 200, 200, grados_rojo, grados_verde);
            g.fillRect(250, 150, 20, 20);
            g.drawString(listado.Producto_2().getNombre(),275,165);
            
            g.setColor(new Color(0,0,200));
            g.fillArc(25, 80, 200, 200, grados_rojo + grados_verde, grados_azul);
            g.fillRect(250, 180, 20, 20);
            g.drawString(listado.Producto_3().getNombre(),275,195);
            
        }
        
    }
    
    public void Repaint(){
        repaint();
    }

}
